### ISSUE TITLE
uninstall script doesn't work on zsh

### ISSUE THREAD

**Issue by GiselleSerate** [GiselleSerate/myaliases#27]
For some reason the `$ABSPATH` variable isn't being set in the `.included`. So this is a more fundamental problem found in the setup file.

**Comment by GiselleSerate** [comment]
Testing reveals that this is not a problem with the setup file. Echoing and saving `$ABSPATH` at the beginning of the uninstall script doesn't work for some reason; its value is blank there too. I don't know why this is; it worked fine on bash.

**Comment by aryam7** [comment]
I might have an idea for why this is happening.
When we create the $ABSPATH variable, we are making it globally accessible (and editable) by all commands that are run after the terminal has started up. This includes our own commands like cds and whatnot.
But an executed script (like uninstall, for example) may or may not have access to those global variables because we don't know whether it is being executed in the same environment as the one that set those global variables to begin with. This makes most sense when you realize that uninstall is being executed by `/bin/sh`, not `/bin/zsh`. This might explain why uninstall worked in a bash environment, since many terminals apparently use `/bin/sh` as bash.
