### ISSUE TITLE
use forks for subl?

### ISSUE THREAD

**Issue by GiselleSerate** [GiselleSerate/myaliases#57]
Maybe not forks (let's overapply 105 woo) but make it not need to occupy the terminal session.

**Comment by GiselleSerate** [comment]
Oops I accidentally an enhancement. Sourcing gives an error but I think it's probably something I forgot to clean up somewhere. As of commit 65abd16012c40b95dcfa53d6a482da256c3002e1.

**Comment by GiselleSerate** [comment]
Completely debugged as of 4dd7bca2afcae396ba0c451ebe6dbec652f433cd.

**Comment by aryarm** [comment]
@GiselleSerate, [here](https://github.com/GiselleSerate/myaliases/commit/13858dfdf5cfabff544a228396c55057c199cbb9#commitcomment-34796737)'s an alternative that I've used for a while.
`ln -s "/mnt/c/Program Files/Sublime Text 3/sublime_text.exe" /usr/local/bin/subl`

Doing it this way ensures that it won't hang your shell. I generally don't think we need aliases for these types of things, since this is nearly as convenient as defining a permanent alias.

In fact, you could probably even create a function for doing this for arbitrary executables. But you would probably have to check whether `/usr/local/bin` is in `$PATH` and if not, find a suitable alternative (perhaps like `~/bin`).
