### ISSUE TITLE
options

### ISSUE THREAD

**Issue by aryam7** [GiselleSerate/myaliases#64]
I'm very, very confused about the best way to use options in a bash script. There are a lot of competing answers on the internet and none of them seem ideal. I'm going to try explaining them here. @GiselleSerate, let me know what you think.
I found a great explanation of three ways to parse options in [this Stack Overflow answer](https://stackoverflow.com/a/14203146). They recommend just using regular bash in the first two methods, both of which seem quite robust, if not a little verbose. The last answer, however, explains that the builtin `getopts` (which I presume was made specifically for this sort of thing) might be better because it's portable and can handle combining options automatically (like using `-vf` instead of `-v -f`).
I looked into `getopts` using [this tutorial](http://wiki.bash-hackers.org/howto/getopts_tutorial). The only downside, it seems, is that it can't handle optional option arguments, like the kind we're planning to use for `-h`. [This Stack Overflow post](https://stackoverflow.com/questions/11517139/optional-option-argument-with-getopts) details some work-arounds.
However, the [second answer in that post](https://stackoverflow.com/a/29754866) describes a much better alternative called _enhanced getopt_, which honestly sounds like the best thing ever. It does all of the stuffs and is supposedly standard on any system. However, a comment to that answer specified that it would be bad for wrapper scipts, which is kinda what we're doing, right? They suggested [this code](https://gist.github.com/kaushalmodi/74e9875d5ab0a2bc1010447f1bee5d0a), instead.

Could we also just use c?

**Comment by GiselleSerate** [comment]
C has workable options code, I can go dig it out of my homework repo.  It can definitely handle optional arguments.

**Comment by aryam7** [comment]
Ah ok sounds good

**Comment by GiselleSerate** [comment]
[Here's](https://drive.google.com/file/d/1TbxjZ9DGhoePMNf8DrIRVYq5ewVaMTeA/view) the writeup for 105's cache lab, which talks about getopt, the C library we used. Also, since this is a public thread, I won't post my code that I wrote for the class, but if we want to use it for reference, we can definitely do that.

**Comment by GiselleSerate** [comment]
Wait wait, I maybe misunderstood your original post. Are we talking about optional flags or optional arguments? Cause optional flags are for sure a thing (actually, it would be pretty dumb if they weren't) but optional arguments are ["not required by POSIX"](https://stackoverflow.com/questions/19604413/getopt-optional-arguments). 

I don't remember, what were we using optional arguments for?

**Comment by aryam7** [comment]
oh hmm yeah I was talking about optional arguments. It seems like POSIX requires that if we have an argument to an option, it be required? That's upsetting.
Actually, it seems like the page you linked to describes the c equivalents of the bash functions that I was talking about when I started this issue.
There's this [enhanced getopt](https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash/29754866#29754866) which handles optional arguments in the correct way, but I bet it isn't POSIX. But apparently, "no GNU system is missing this (e.g. any Linux has it)" and it's "available on most 'bash-systems'"

**Comment by aryarm** [comment]
Alright, I'm going to close this issue because I feel like I now have a better handle on this.

The answer is that if you want to be super portable, you have to write your own code to handle the options. But for most cases (ie on non-Solaris machines), you can just use `getopts`, which is POSIX. The main disadvantage to this is that it doesn't handle long options. If you want those, you should use the enhanced `getopt` which does all of the things. The only downside is that it is only available on Linux machines (and not installed by default on Macs).
